import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import authRouter from "./routes/auth.routes.js";
import userRouter from "./routes/user.routes.js";
import chatRouter from "./routes/chat.routes.js";
import healthRouter from "./routes/health.routes.js";
import reminderRouter from "./routes/reminder.routes.js";
import taskRouter from "./routes/task.routes.js";
import emailRouter from "./routes/email.routes.js";
import calendarRouter from "./routes/calendar.routes.js";
import memoryRouter from "./routes/memory.routes.js";
import documentRouter from "./routes/document.routes.js";
import agentRouter from "./routes/agent.routes.js";
import workspaceRouter from "./routes/workspace.routes.js";
import analyticsRouter from "./routes/analytics.routes.js";
import { createApiRateLimiter } from "./middleware/rateLimiter.js";
import { createSessionMiddleware } from "./middleware/session.middleware.js";
import { errorMiddleware } from "./middleware/error.middleware.js";

export const createApp = () => {
  const app = express();
  app.use(cors({ origin: process.env.FRONTEND_URL, credentials: true }));
  app.use(express.json());
  app.use(cookieParser());
  app.use(createSessionMiddleware());
  app.use(createApiRateLimiter());
  app.use("/public", express.static("public"));
  app.get("/", (req, res) => res.send("Api is working!!"));
  app.use("/api/auth", authRouter);
  app.use("/api/user", userRouter);
  app.use("/api/chat", chatRouter);
  app.use("/api/reminders", reminderRouter);
  app.use("/api/tasks", taskRouter);
  app.use("/api/emails", emailRouter);
  app.use("/api/calendar", calendarRouter);
  app.use("/api/memory", memoryRouter);
  app.use("/api/documents", documentRouter);
  app.use("/api/agent-runs", agentRouter);
  app.use("/api/workspaces", workspaceRouter);
  app.use("/api/analytics", analyticsRouter);
  app.use("/health", healthRouter);
  app.use(errorMiddleware);
  return app;
};
